FROM openjdk:9

ENV HADOOP_VER=2.7.3 HADOOP_PREFIX=/opt/hadoop

RUN apt-get update 
 add bash ca-certificates gnupg openssl su-exec tar nginx curl \
 && apk --no-cache --update --repository https://dl-3.alpinelinux.org/alpine/edge/community/ add xmlstarlet \
 && update-ca-certificates \
\
# Set up directories
 && mkdir -p $HADOOP_PREFIX \
 && mkdir -p /var/lib/hadoop \
\
# Download Hadoop
 && wget -O /tmp/KEYS https://dist.apache.org/repos/dist/release/hadoop/common/KEYS \
 && gpg --import /tmp/KEYS \
 && wget -q -O /tmp/hadoop.tar.gz http://apache.mirror.digitalpacific.com.au/hadoop/common/hadoop-$HADOOP_VER/hadoop-$HADOOP_VER.tar.gz \
 && wget -O /tmp/hadoop.asc https://dist.apache.org/repos/dist/release/hadoop/common/hadoop-$HADOOP_VER/hadoop-$HADOOP_VER.tar.gz.asc \
 && gpg --verify /tmp/hadoop.asc /tmp/hadoop.tar.gz \
 && tar -xzf /tmp/hadoop.tar.gz -C $HADOOP_PREFIX  --strip-components 1 \
\
# Set up permissions
 && addgroup -S hadoop \
 && adduser -h $HADOOP_PREFIX -G hadoop -S -D -H -s /bin/false -g hadoop hadoop \
 && chown -R hadoop:hadoop $HADOOP_PREFIX \
 && chown -R hadoop:hadoop /var/lib/hadoop \
\
# Enable snappy
 && ln -s /usr/lib/libsnappy.so.1.3.1 $HADOOP_PREFIX/lib/native/libsnappy.so \
 && echo export JAVA_LIBRARY_PATH="${HADOOP_PREFIX}/lib:${HADOOP_PREFIX}/lib/native" >> /opt/hadoop/etc/hadoop/hadoop-env.sh \
\
# Clean up
 && apk del gnupg openssl tar \
 && rm -rf /tmp/* /var/tmp/* /var/cache/apk/*

VOLUME ["/var/lib/hadoop"]

ADD ["run-hadoop.sh", "/"]
ADD ["/roles", "/roles"]

COPY nginx.default.conf /etc/nginx/conf.d/default.conf

#      Namenode              Datanode                     Journalnode
EXPOSE 8020 9000 50070 50470 50010 50075 50475 1006 50020 8485 8480 8481

CMD ["/run-hadoop.sh"]